//! Embeds the Windows version resource and the app icon into `venu.exe`.
//!
//! Without this the exe carries no version information at all, which shows up
//! everywhere an installed app is listed: Explorer's properties page, the
//! Start Menu entry, the "Apps & features" list — and it would leave the
//! installer without a version to read.

fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    let mut res = winresource::WindowsResource::new();

    // Pack the Cargo version (0.3.0) into the FILEVERSION quad the Windows
    // shell displays: major.minor.patch.rev0.
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".to_string());
    let mut parts = version.split('.').map(|p| p.parse::<u64>().unwrap_or(0));
    let (major, minor, patch) = (
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
    );
    let packed = (major << 48) | (minor << 32) | (patch << 16);

    res.set("FileDescription", "Venu - Dynamic Notch for Windows");
    res.set("ProductName", "Venu");
    res.set("FileVersion", &version);
    res.set("ProductVersion", &version);
    let _ = res.set_version_info(winresource::VersionInfo::FILEVERSION, packed);
    let _ = res.set_version_info(winresource::VersionInfo::PRODUCTVERSION, packed);

    // The committed icon is generated by scripts/gen-icon.ps1 from the same
    // procedural pattern the app draws for its window and tray icons.
    if std::path::Path::new("assets/venu.ico").exists() {
        res.set_icon("assets/venu.ico");
    }

    res.compile()
        .expect("failed to compile the Windows resource for venu.exe");
}
